# Generated by Django 3.2 on 2021-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
